title: Bakery GOODS
description: A Gallery of Open-source Demo Scripts
baseurl: "/goods"
author: Austin Cory Bart (acbart@udel.edu)    https://acbart.com
url: "https://python-bakery.github.io"
remote_theme: pages-themes/dinky@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: python
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
